// web/src/routes/admin/login.tsx
import { createFileRoute, useNavigate, redirect } from '@tanstack/react-router'
import { useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import { useStore } from '@tanstack/react-store'
import { authApi } from '@/lib/api.auth'
import { authStore, authActions } from '@/store/auth'
import { useLoginForm } from '@/forms/auth.forms'
import { Lock, Mail, Eye, EyeOff } from 'lucide-react'

export const Route = createFileRoute('/admin/login')({
  beforeLoad: () => {
    const authState = authStore.state
    // If authenticated, redirect to dashboard
    if (authState.isAuthenticated) {
      throw redirect({
        to: '/admin/dashboard',
      })
    }
  },
  component: LoginPage,
})

function LoginPage() {
  const navigate = useNavigate()
  const [showPassword, setShowPassword] = useState(false)
  const form = useLoginForm()

  const loginMutation = useMutation({
    mutationFn: authApi.login,
    onSuccess: (data) => {
      // Save auth state
      authActions.login(data.user, {
        accessToken: data.accessToken,
        refreshToken: data.refreshToken,
      })
      // Redirect to admin dashboard
      navigate({ to: '/admin/dashboard' })
    },
    onError: (err: any) => {
      form.setError('root', {
        message: err.message || 'Đăng nhập thất bại. Vui lòng thử lại.',
      })
    },
  })

  const onSubmit = (data: { email: string; password: string }) => {
    loginMutation.mutate(data)
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-orange-50 to-orange-100 px-4">
      <div className="max-w-md w-full bg-white rounded-2xl shadow-2xl p-8">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="mx-auto mb-4 w-16 h-16 bg-orange-500 rounded-full flex items-center justify-center shadow-lg">
            <Lock className="w-10 h-10 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Chào mừng trở lại!
          </h1>
          <p className="text-gray-600">Đăng nhập vào hệ thống quản lý</p>
        </div>

        {/* Error Message */}
        {form.formState.errors.root && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-sm text-red-600">
              {form.formState.errors.root.message}
            </p>
          </div>
        )}

        {/* Login Form */}
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
          {/* Email Input */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Email
              <span className="text-red-500">*</span>
            </label>
            <div className="relative">
              <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                type="email"
                {...form.register('email')}
                placeholder="Nhập email của bạn"
                className={`w-full pl-10 pr-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent transition-all ${
                  form.formState.errors.email
                    ? 'border-red-300'
                    : 'border-gray-300'
                }`}
              />
            </div>
            {form.formState.errors.email && (
              <p className="mt-1 text-sm text-red-600">
                {form.formState.errors.email.message}
              </p>
            )}
          </div>

          {/* Password Input */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Mật khẩu
              <span className="text-red-500">*</span>
            </label>
            <div className="relative">
              <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                type={showPassword ? 'text' : 'password'}
                {...form.register('password')}
                placeholder="Nhập mật khẩu"
                className={`w-full pl-10 pr-12 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent transition-all ${
                  form.formState.errors.password
                    ? 'border-red-300'
                    : 'border-gray-300'
                }`}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700 transition-colors"
              >
                {showPassword ? (
                  <EyeOff className="w-5 h-5" />
                ) : (
                  <Eye className="w-5 h-5" />
                )}
              </button>
            </div>
            {form.formState.errors.password && (
              <p className="mt-1 text-sm text-red-600">
                {form.formState.errors.password.message}
              </p>
            )}
          </div>

          {/* Submit Button */}
          <button
            type="submit"
            disabled={loginMutation.isPending}
            className="w-full bg-orange-500 hover:bg-orange-600 text-white font-semibold py-3 px-4 rounded-lg transition-colors shadow-lg shadow-orange-500/50 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loginMutation.isPending ? (
              <span className="flex items-center justify-center">
                <svg
                  className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  ></circle>
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  ></path>
                </svg>
                Đang đăng nhập...
              </span>
            ) : (
              'Đăng nhập'
            )}
          </button>
        </form>

        {/* Footer */}
        <div className="mt-6 text-center">
          <p className="text-sm text-gray-600">Hệ thống quản lý thuê xe P2P</p>
        </div>
      </div>
    </div>
  )
}

// web/src/pages/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '@/services/auth.service';
import { ButtonComponent } from '@/components/button/button.component';
import { InputComponent } from '@/components/input/input.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, ButtonComponent, InputComponent],
  templateUrl: './login.component.html',
})
export class LoginComponent {
  private readonly fb = inject(FormBuilder);
  private readonly authService = inject(AuthService);
  private readonly router = inject(Router);

  loginForm: FormGroup;
  loading: boolean = false;
  error: string = '';
  showPassword: boolean = false;

  constructor() {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(8)]],
    });
  }

  onSubmit(): void {
    if (this.loginForm.invalid) {
      return;
    }

    this.loading = true;
    this.error = '';

    const { email, password } = this.loginForm.value;

    this.authService.login({ email, password }).subscribe({
      next: () => {
        this.loading = false;
        this.router.navigate(['/']);
      },
      error: (err) => {
        this.loading = false;
        this.error = err.error?.message || 'Đăng nhập thất bại. Vui lòng thử lại.';
        console.error('Login error:', err);
      },
    });
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  navigateToForgotPassword(): void {
    this.router.navigate(['/forgot-password']);
  }

  navigateToRegister(): void {
    this.router.navigate(['/register']);
  }
}

<div
  class="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-50 to-primary-100 px-4"
>
  <div class="max-w-md w-full bg-white rounded-2xl shadow-2xl p-8">
    <!-- Header -->
    <div class="text-center mb-8">
      <div
        class="mx-auto mb-4 w-16 h-16 bg-primary-500 rounded-full flex items-center justify-center shadow-lg"
      >
        <svg class="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
          />
        </svg>
      </div>
      <h1 class="text-3xl font-bold text-gray-900 mb-2">Chào mừng trở lại!</h1>
      <p class="text-gray-600">Đăng nhập để tiếp tục</p>
    </div>

    <!-- Error Message -->
    @if (error) {
      <div class="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
        <p class="text-sm text-red-600">{{ error }}</p>
      </div>
    }

    <!-- Login Form -->
    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <!-- Email Input -->
      <app-input
        formControlName="email"
        label="Email"
        type="email"
        placeholder="Nhập email của bạn"
        [required]="true"
        [error]="
          loginForm.get('email')?.invalid && loginForm.get('email')?.touched
            ? 'Email không hợp lệ'
            : ''
        "
      />

      <!-- Password Input -->
      <div class="mb-6">
        <label class="block text-sm font-medium text-gray-700 mb-2">
          Mật khẩu
          <span class="text-red-500">*</span>
        </label>
        <div class="relative">
          <input
            [type]="showPassword ? 'text' : 'password'"
            formControlName="password"
            placeholder="Nhập mật khẩu"
            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent pr-12 transition-all"
          />
          <button
            type="button"
            (click)="togglePasswordVisibility()"
            class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
          >
            @if (showPassword) {
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"
                />
              </svg>
            } @else {
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                />
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
                />
              </svg>
            }
          </button>
        </div>
        @if (loginForm.get('password')?.invalid && loginForm.get('password')?.touched) {
          <p class="mt-1 text-sm text-red-600">Mật khẩu phải có ít nhất 8 ký tự</p>
        }
      </div>

      <!-- Submit Button -->
      <app-button
        type="submit"
        variant="primary"
        [disabled]="loginForm.invalid || loading"
        [loading]="loading"
        class="mb-4"
      >
        Đăng nhập
      </app-button>

      <!-- Register Link -->
      <div class="text-center mt-4">
        <p class="text-sm text-gray-600">
          Chưa có tài khoản?
          <button
            type="button"
            (click)="navigateToRegister()"
            class="text-primary-600 hover:text-primary-700 font-bold ml-1 transition-colors"
          >
            Đăng ký ngay
          </button>
        </p>
      </div>
    </form>
  </div>
</div>
